spring:
  application:
    name: ITLens
  datasource:
    url: jdbc:postgresql://localhost:5432/itlens
    username: ituser
    password: ouchin55edcx
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update