spring:
  application:
    name: BACKEND

  datasource:
    url: jdbc:postgresql://localhost:5432/resto_manage
    username: hamza
    password: hamza

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Africa/Casablanca

  jackson:
    time-zone: Africa/Casablanca

  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs
