spring:
  profiles:
    active: dev
  security:
    filter:
      order: 10

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds